#	$OpenBSD: Makefile,v 1.4 2005/05/16 15:22:46 espie Exp $
# $FreeBSD: head/usr.bin/patch/Makefile 255014 2013-08-29 00:38:24Z pfg $

PROG=	patch

SRCS=	backupfile.c inp.c mkpath.c patch.c pch.c util.c

.include <bsd.prog.mk>
